apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nestjs-metrics
  name: nestjs-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-metrics
  template:
    metadata:
      labels:
        app: nestjs-metrics
    spec:
      containers:
      - image: tonysd/metrics
        name: metrics
        ports:
        - containerPort: 3000
        resources: {}
